Task/Controllers/MarketTeamLeadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class MarketTeamLeadController : Controller
    {
        //
        // GET: /MarketTeamLead/
        private Database1Entities1 db = new Database1Entities1();
        private int userID()
        {
            User m = new User();
            m.ID = Convert.ToInt32(Session["UserID"]);
            int id = m.ID;
            return id;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult requests(int id = 0)
        {
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            ViewBag.MD_id = new SelectList(db.Users, "ID", "FirstName", team.MD_id);
            ViewBag.Trainee_id = new SelectList(db.Users, "ID", "FirstName", team.Trainee_id);
            return View(team);
        }

        public ActionResult listA()
        {
            int I = Convert.ToInt32(Session["UserID"]);
            var ctx = new Database1Entities1();
            var l = ctx.Teams.Where(u => u.MTL_id == I && u.IsApproved == 1).ToList<Team>();
            return View(l.ToList());
        }

        public ActionResult listD()
        {
            int I = Convert.ToInt32(Session["UserID"]);
            var ctx = new Database1Entities1();
            var l = ctx.Teams.Where(u => u.MTL_id == I && u.IsApproved == 0).ToList<Team>();
            return View(l.ToList());
        }
        //
        // POST: /team/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult requests(Team team)
        {
            if (ModelState.IsValid)
            {
                db.Entry(team).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MD_id = new SelectList(db.Users, "ID", "FirstName", team.MD_id);
            ViewBag.Trainee_id = new SelectList(db.Users, "ID", "FirstName", team.Trainee_id);
            return View(team);
        }
        // 3. Remove Projects (leave the project).
        /*       public ActionResult removeProjects()
        {
            int id = userID();
            return View(db.Projects.Where(a => a.user_id == id).ToList());
        }

        [HttpGet]
        public ActionResult removeProject(long id = 0)
        {
            Project project = db.Projects.Find(id);
            return View(project);

        }

        [HttpPost, ActionName("removeProject")]    // the same as  [HttpPost] removeProject
        public ActionResult removProjectConfirmed(long id = 0)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        ///2. Remove MT (remove Undesired member).

        public ActionResult deleteTrainee()
        {

            // var list = db.Teams.Where(u => u.user_type == 3);
            //return View(db.Users.Where(u=>u.user_type == 3).ToList());
            return View(db.Teams.Where(u => u.MTL_id == userID()).ToList());
        }


        [HttpGet]
        public ActionResult removeTrainees(long id = 0)
        {
            /*
            User trainee = db.Users.Find(id);
            return View(trainee);
            

            var trainees = db.Teams.Where(a => a.Proj_id == id).ToList();
            List<User> traineeList = new List<User>();
            foreach (var item in trainees)
            {
                User user = (User)db.Users.Where(a => a.ID == item.Trainee_id && a.user_type == 4);
                traineeList.Add(user);
            }
            return View(traineeList.ToList());
        }

        [HttpGet]
        public ActionResult removeTrainee(long id = 0)
        {
            Project project = db.Projects.Find(id);
            return View(project);

        }

        [HttpPost, ActionName("removeTrainee")]    // the same as  [HttpPost] removeTrainee
        public ActionResult removTraineeConfirmed(long id = 0)
        {
            User trainee = db.Users.Find(id);
            db.Users.Remove(trainee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        ///Checking His Profile to see the requests
        ///
        public ActionResult CheckRequest()
        {
            int id = userID();
            var teams = db.Teams.Where(a => a.MTL_id == id).ToList();
            List<Project> projects = new List<Project>();
            foreach (var item in teams)
            {
                Project tempProject = (Project)db.Projects.Where(a => a.ID == item.Proj_id);
                projects.Add(tempProject);
            }
            return View(projects.ToList());
        }

        public ActionResult Join(int id = 0)
        {

            return RedirectToAction("index");
        }
        public ActionResult Refuse()
        {

            return RedirectToAction("Index");
        }


        */
    }





}

Task/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class UserController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();

        //
        // GET: /User/

        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.User);
            return View(projects.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User objUser,string returnUrl)
    {
        TempData["notice"] = "Successfully registered";
            if (objUser.Email == null || objUser.JobDescription == null || objUser.LastName == null || objUser.Mobile == null || objUser.Password == null || objUser.user_type == null)
            {
                ModelState.AddModelError("", "Empty Data");
                return View(objUser);
            }
            else if (ModelState.IsValid)
            {
                db.Users.Add(objUser);
                db.SaveChanges();
            }
            if (string.IsNullOrEmpty(returnUrl) && Request.UrlReferrer != null)
                returnUrl = Server.UrlEncode(Request.UrlReferrer.PathAndQuery);

            if (Url.IsLocalUrl(returnUrl) && !string.IsNullOrEmpty(returnUrl))
            {
                ViewBag.ReturnURL = returnUrl;
            }
            return View(objUser);
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(User objUser)
        {
            if (ModelState.IsValid)
            {
                
                    var obj = db.Users.Where(a => a.Email.Equals(objUser.Email) && a.Password.Equals(objUser.Password)).FirstOrDefault();
                    if (obj != null)
                    {
                        Session["UserID"] = obj.ID.ToString();
                        Session["UserName"] = obj.FirstName.ToString();
                        Session["UserNameTwo"] = obj.LastName.ToString();
                        Session["UserType"] = obj.user_type.ToString();
                        if(obj.Photo != null)
                        Session["UserPhoto"] = obj.Photo.ToString();
                        return RedirectToAction("Route");
                    }
                }
            
            return View(objUser);
        }

        public ActionResult Route()
        {
            if (Session["UserID"] != null)
            {
                if (String.Equals(Session["UserType"], "1"))
                    return RedirectToAction("Index","Admin");

                else if (String.Equals(Session["UserType"], "2"))
                    return RedirectToAction("Index", "MarketDir");

                else if (String.Equals(Session["UserType"], "3"))
                    return RedirectToAction("Index", "MarketTeamLead");

                else if (String.Equals(Session["UserType"], "4"))
                    return RedirectToAction("Index", "MarketTrainee");

                else if (String.Equals(Session["UserType"], "5"))
                    return RedirectToAction("Index", "Customer");
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        public ActionResult listProfile()
        {
            User m = new User();
            m.ID = Convert.ToInt32(Session["UserID"]);
            int n=m.ID;
            var ctx = new Database1Entities1();
            //var l = ctx.Users.SqlQuery("Select * from User where ID=1").ToList();
           var l= ctx.Users.Where(u => u.ID == n).Select(u => u);
            return View(l);

        }
        public ActionResult Update(int id = 0)
        {
            User u = db.Users.Find(id);
            if (u == null)
            {
                return HttpNotFound();
            }
            ViewBag.user_id = new SelectList(db.Users, "ID", "FirstName", u.ID);
            return View(u);
        }

        [HttpPost]
        public ActionResult Update(User u,HttpPostedFileBase file)
        {
            TempData["notice"] = "Successfully Updated";
            u.user_type = Convert.ToInt32(Session["UserType"]);
            if (u.Photo == null && file == null )
                ModelState.AddModelError("", "Photo Is empty , upload it please");
            else
            {
                if (file != null)
                {
                    var allowedExtensions = new[] { ".Jpg", ".png", ".jpg", "jpeg" };
                    if (!(allowedExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.')))))
                    {
                        ModelState.AddModelError("", "Wrong File ");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var paths = Path.Combine(Server.MapPath("~/Img"), fileName);
                        file.SaveAs(paths);
                        u.Photo = "/Img/" + fileName;
                    }
                }
                    if (ModelState.IsValid)
                    {
                        db.Entry(u).State = EntityState.Modified;
                        db.SaveChanges();
                    }

                }
            return View(u);
        }

        }
}

Task/Controllers/teamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task.Models;

namespace Task.Controllers
{
    public class teamController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();

        //
        // GET: /team/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /team/Details/5

        public ActionResult Details(int id = 0)
        {
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        //
        // GET: /team/Create

        public ActionResult Create()
        {
            int WantedID = Convert.ToInt32(Session["UserID"]);
            ViewBag.IDW = WantedID;
            ViewBag.user_trainee = new SelectList(db.Users.Where(s => s.user_type == 4), "ID", "FirstName");
            ViewBag.user_mtl = new SelectList(db.Users.Where(q => q.user_type == 3), "ID", "FirstName");
            ViewBag.proj_id = new SelectList(db.Projects.Where(o => o.Status == 0), "ID", "Title");
            return View();
        }

        //
        // POST: /team/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Team team)
        {
            if (ModelState.IsValid)
            {
                db.Teams.Add(team);
                db.SaveChanges();
                return RedirectToAction("Index","MarketTeamLead");
            }

            ViewBag.MD_id = new SelectList(db.Users, "ID", "FirstName", team.MD_id);
            ViewBag.Trainee_id = new SelectList(db.Users, "ID", "FirstName", team.Trainee_id);
            return View(team);
        }

        //
        // GET: /team/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            ViewBag.MD_id = new SelectList(db.Users, "ID", "FirstName", team.MD_id);
            ViewBag.Trainee_id = new SelectList(db.Users, "ID", "FirstName", team.Trainee_id);
            return View(team);
        }

        //
        // POST: /team/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Team team)
        {
            if (ModelState.IsValid)
            {
                db.Entry(team).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "MarketTeamLead");
            }
            ViewBag.MD_id = new SelectList(db.Users, "ID", "FirstName", team.MD_id);
            ViewBag.Trainee_id = new SelectList(db.Users, "ID", "FirstName", team.Trainee_id);
            return View(team);
        }

        //
        // GET: /team/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        //
        // POST: /team/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Team team = db.Teams.Find(id);
            db.Teams.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Index","MarketTeamLead");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Task/Views/MarketTeamLead/CheckRequest.cshtml
@model IEnumerable<Task.Models.Project>

@{
    ViewBag.Title = "CheckRequest";
}

<h2>CheckRequest</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>

            <td>
                @Html.ActionLink("Join", "Join", new { id = item.ID }) |
                @Html.ActionLink("Refuse", "Refuse", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Task/Views/MarketTeamLead/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<style>
    li {
    color:#a53434;
    font-size:x-large;
    font-family:Cambria;
    }
    #am {
    font-size:xx-large
    }
    h2 {
    text-align:center
    }
</style>


<div class="container">
    <h1>Welcome Our Leader</h1>
  <h2>Your Control Panel</h2>
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a id="am" data-toggle="collapse" data-parent="#accordion" href="#collapse1">Show Controls</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse in">
        <div class="panel-body">
      <ul style="list-style:none">
      <li class="list-group-item list-group-item-success">

@Html.ActionLink("Teams", "listA")

      </li>
                <li class="list-group-item list-group-item-info">
@Html.ActionLink("Waited Requests", "listD")
                </li>
                <li class="list-group-item list-group-item-warning">
@Html.ActionLink("My Profile", "listProfile","User")
                </li>
                <li class="list-group-item list-group-item-danger">

                </li>

      <li class="list-group-item list-group-item-success">

                </li>
            </ul>
        </div>
      </div>
    </div>



    </div>
    <span style="margin-left:1000px;">
 @Html.ActionLink("Logout", "Index","User",new object { },new { @class = "btn btn-danger"})
    </span>
  </div> 

<br />
<br />
<br />
<br />

Task/Views/MarketTeamLead/deleteTrainee.cshtml
@model IEnumerable<Task.Models.User>

@{
    ViewBag.Title = "deleteTrainee";
}

<h2>deleteTrainee</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mobile)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.ActionLink("Delete", "removeTrainees", new { id = item.ID })
            </td>
        </tr>
    }

</table>

Task/Views/MarketTeamLead/listA.cshtml
@model IEnumerable<Task.Models.Team>

@{
    ViewBag.Title = "listA";
}
<style>
    tr, td, th {
    margin:30px;
    padding:30px;
    height:100px;
    }
</style>
<div class="container">
<table class="table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Trainee_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MD_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proj_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MTL_id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Trainee_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MD_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proj_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MTL_id)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit","team", new { id=item.ID }) 
        </td>
    </tr>
}

</table>
</div>

Task/Views/MarketTeamLead/listD.cshtml
@model IEnumerable<Task.Models.Team>

@{
    ViewBag.Title = "listD";
}
<style>
    tr, td, th {
    margin:30px;
    padding:30px;
    height:100px;
    }
</style>
<div class="container">

    @if (Model.Count() > 0){
<table class="table-bordered">
       <tr>
        <th>
            @Html.DisplayNameFor(model => model.Trainee_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MD_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proj_id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsApproved)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MTL_id)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Trainee_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MD_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proj_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsApproved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TeamName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MTL_id)
        </td>
        <td>
            @Html.ActionLink("Accept", "requests", new { id=item.ID }) 
        </td>
    </tr>
}

</table>
    } 
  else{
    <h2> There's No Records</h2>
    }   
    </div>

Task/Views/MarketTeamLead/removeProject.cshtml
@model Task.Models.Project

@{
    ViewBag.Title = "removeProject";
}

<h2>removeProject</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.price)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Task/Views/MarketTeamLead/removeProjects.cshtml
@model IEnumerable<Task.Models.Project>

@{
    ViewBag.Title = "removeProject";
}

<h2>removeProject</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>

            <td>
                @Html.ActionLink("Delete", "removeProject", new { id = item.ID }) |

            </td>
        </tr>
    }

</table>

Task/Views/MarketTeamLead/removeTrainee.cshtml
@model Task.Models.User

@{
    ViewBag.Title = "removeTrainee";
}

<h2>removeTrainee</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>User</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.FirstName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FirstName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.LastName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LastName)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Mobile)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mobile)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Task/Views/MarketTeamLead/removeTrainees.cshtml
@model IEnumerable<Task.Models.Team>

@{
    ViewBag.Title = "removeTrainees";
}

<h2>removeTrainees</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeamName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink("Remove Trainees", "removeTrainee", new { id = item.Proj_id })
            </td>
        </tr>
    }

</table>

Task/Views/MarketTeamLead/requests.cshtml
@model Task.Models.Team

@{
    ViewBag.Title = "Edit";
}
<div class="container">
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.ID)
           @Html.HiddenFor(model => model.Trainee_id)
           @Html.HiddenFor(model => model.MD_id)
          @Html.HiddenFor(model => model.Proj_id)
     <input type="hidden" name="IsApproved" value="1" />
               @Html.HiddenFor(model => model.TeamName)
               @Html.HiddenFor(model => model.MTL_id)
        
          <p>
            <input type="submit" class="btn btn-info" value="JOIN" />
            
    @Html.ActionLink("Cancel", "Index", null, new { @class="btn btn-info"})
                  </p>

    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
    </div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}